	Feature: Inicio de sesión en Battle.net

  Scenario: Verificar si se logra iniciar sesión tras el ingreso de credenciales válidas y ejecutar videojuego
    * robot { window: 'Iniciar sesión en Battle.net', fork: 'C:/Program Files (x86)/Battle.net/Battle.net.exe', retryCount: 10 }
    * delay(3000)
    * input("dffgsjk__454ASD$%dd" + Key.ENTER)
    * delay(8000)
    * windowOptional('Battle.net').input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.TAB)
    * input(Key.ENTER)
    * delay(28000)
    * windowOptional('Overwatch').input(Key.ENTER)
    * input("Esto seria todo....Adios")
    * delay(5000)
    * screenshot()
    * windowOptional('Overwatch').locate('Close').click()
